apiVersion: v1
kind: Service
metadata:
  name: iot-app-service
  namespace: dev
spec:
  selector:
    app: iot-app
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: ClusterIP
